### ISSUE TITLE
Use parseFloat instead of parseInt when parsing the SVG elements ?

### ISSUE THREAD

**Issue by Zulko** [ismay/coarse#17]
Throughout [utils.js](https://github.com/ismay/coarse/blob/d604c72e1289b8a4cf7f5cd5cf81584f4c8b39d3/lib/utils.js#L1-L66) SVG properties are retrieved using ``parseInt`` but these properties could very well be floats, e.g. a stroke width of ``0.5``, so parseFloat may be better to avoid loosing precision.

**Comment by ismay** [comment]
Oh yeah, you're right 👍

**Comment by ismay** [comment]
Actually, both will fail entirely for values that include a unit (em, rem etc.). But what we accept here as allowed values also depends on what rough.js accepts.

**Comment by ismay** [comment]
So I checked, and roughjs expects pixel values for fillWeight, stroke and hachureGap. So in that case only an int makes sense. So we don't need parseFloat here. Closing, but let me know if I'm overlooking something.

**Comment by Zulko** [comment]
In SVG, properties are expressed in pixel units by default I think. But "1.5 pixel" is a thing, and a line with a width of 1.5 pixels is thicker than a line with a width of 1 pixel (there is antialiasing involved), so all these attributes should be parsed as float.

See [this test HTML](https://gist.github.com/Zulko/3dff47d3b54a8299ec63303d11f79cf2) and try and change some values with floats to see the difference.

**Comment by ismay** [comment]
> But "1.5 pixel" is a thing, and a line with a width of 1.5 pixels is thicker than a line with a width of 1 pixel (there is antialiasing involved), so all these attributes should be parsed as float.

From what I’ve read, it is very dependent on the context how fractional pixels are interpreted though. Depending on the way it’s rendered there might be a visual difference, yes.

But does rough actually expect ints or floats? Does it use the extra precision? Maybe it rounds all input for example.

And I’d be interested in whether or not fractional pixels are actually meant to generate different visual output according to the spec? Or is that just a browser thing?

If it is meaningful according to the svg spec, and roughjs does something with it then I’d agree that parsefloat would be the best. It does feel a bit academic for a plugin that generates imprecise output though 😋 

But let’s keep it open, and if anyone can answer the above questions we know what to do!

**Comment by Zulko** [comment]
It seems that you are assuming that pixel values only make sense when they are integers. In SVG, it is very frequent and natural to have non-integer values of pixels, because objects are not drawn pixel-wise, they are drawn with anti-aliasing.

Take a 2px straight line with a 45deg slope. At no point is the line actually 2px thick, it is the combination of black and grey pixels that confer the impression of a 2px thickness. So another combination of pixels could also represent a 2.5px thickness.

Another example to explain why fractional pixel units happen a lot: draw a square with inkscape or Adobe Illustrator, and set the stroke width to 1px. Now enlarge the square by 50%. The resulting square has a stroke-width of 1.5px. If it were 1px, or 2px, the enlargement would change the aspect of the square, so it has to be 1.5px.

**Comment by ismay** [comment]
> It seems that you are assuming that pixel values only make sense when they are integers. In SVG, it is very frequent and natural to have non-integer values of pixels, because objects are not drawn pixel-wise, they are drawn with anti-aliasing.

No I'm not assuming that. I'm wondering what the spec actually says on whether such values are valid. I rarely deal with the innards of an svg, so I have no idea. I looked around for documentation on it and did not get find a clear answer.

And I'm wondering how rough-js deals with floats. I don't know that either. So that's why I'm saying that I'd like to research that before implementing it.

I understand your reasoning, and you might know tons more than me on the subject, but I'd like to make sure that what we're doing makes sense and will work as we expect, beyond just trusting what you're saying.

**Comment by Zulko** [comment]
Fair enough. In the code the different options are [typed here](https://github.com/pshihn/rough/blob/938faec490e5a9125dd3b3c00cbab57c9dc6d33d/src/core.ts#L15-L29). They all have the ``number`` type, which in typescript [refers to floats](https://www.typescriptlang.org/docs/handbook/basic-types.html). Most examples feature integer parameters though, but for instance [this one](https://github.com/pshihn/rough/blob/05fb7ab08cfae66b3db6185b1d144baf36eb9c5e/docs/examples/contributed/balloon-animation.html#L112-L113) has floats for hachureAngle and hachureGap.

**Comment by ismay** [comment]
Ok cool, thanks 👍. Would you mind submitting a pr with the changes?
