### ISSUE TITLE
The path element does not show in converted svg

### ISSUE THREAD

**Issue by hupili** [ismay/coarse#22]
Original: (produced by plotly's Python binding)

<img width="573" alt="screenshot 2018-12-26 at 12 16 41 pm" src="https://user-images.githubusercontent.com/1227160/50431766-34b24f00-0908-11e9-8171-eba7b86c1e0e.png">

The converted version:

<img width="1305" alt="screenshot 2018-12-26 at 12 15 54 pm" src="https://user-images.githubusercontent.com/1227160/50431770-3a0f9980-0908-11e9-8d47-de340b7b2df0.png">

It seems the conversion is successful -- we can tell from the `d` of new `path`. However this path does not show on the coarse version. It corresponds to the topmost poly-line.

Following are the original files of test images:

[Test Images.zip](https://github.com/ismay/coarse/files/2709439/Test.Images.zip)

Generated via:

```
node bin/index.js hidden-ratio.svg test.svg
```

**Comment by hupili** [comment]
Removing this attribute can solve the problem:

<img width="255" alt="wechatimg48" src="https://user-images.githubusercontent.com/1227160/50432327-00d92880-090c-11e9-9239-b6ad75c2646a.png">

Thanks @RoberMac for the trouble shooting.

Seems removing this attribute requires some domain knowledge of the upstream and fix had better be on plotly side (or in between plotly and coarse).

**Comment by ismay** [comment]
Thanks for sharing this 👍

> Seems removing this attribute requires some domain knowledge of the upstream and fix had better be on plotly side (or in between plotly and coarse).

Allright. Yeah there’s a lot of styles and other attributes that could conflict with the generated svg. I think it’s difficult to find a generic solution to this. I’ll close this as it’s resolved.
